<?php
/*
 * Copyright (C) 2009-2011 Jeremiah Mahler <jmmahler@gmail.com>
 *
 * This file is part of QuizMaker.
 * 
 * QuizMaker is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QuizMaker is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with QuizMaker.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

$xs = $this->tests;

$title = "Edit Test";
$this->headTitle($title);

$test_id = $this->test_id;

$canc_url = $this->url(array(
                'controller' => 'tests',
                'action' => 'view',
                'test_id' => $test_id));
?>

<div class="box">

<h2 class="header"><?php echo $title; ?></h2>

<div style="margin: 20px;">
<?php echo $this->form; ?>
<p><a href="<?php echo $canc_url; ?>">&lt;-- CANCEL</a></p>
</div>


</div>

