<?php
/*
 * Copyright (C) 2009-2011 Jeremiah Mahler <jmmahler@gmail.com>
 *
 * This file is part of QuizMaker.
 * 
 * QuizMaker is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QuizMaker is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with QuizMaker.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

$xs = $this->tests;

$title = "Create New Test";
$this->headTitle($title);

echo "<div class=\"box\">";

echo "<h2 class=\"header\">$title</h2>";

echo $this->form;

#echo "<table class=\"center\" style=\"width: 85%;\">";
#echo "<tr><th>description</th><th>create date</th></tr>";


$index_url = $this->url(array(
                'controller' => 'tests',
                'action'     => 'index',),
            null, true);

#echo "<tr><td colspan=\"2\"><a href=\"$new_url\">create new test</a></td></tr>";


#echo "</table>";

echo "</div>";  # class="box"

?>

