<?php
/*
 * Copyright (C) 2009-2011 Jeremiah Mahler <jmmahler@gmail.com>
 *
 * This file is part of QuizMaker.
 * 
 * QuizMaker is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * QuizMaker is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with QuizMaker.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

$ps = $this->problems;

echo "<div class=\"box\">";
echo "<h2 class=\"header\">Problems</h2>";

echo "<table class=\"center\" style=\"width: 85%;\">";
echo "<tr><th>description</th><th>created</th><th>add?</th></tr>";

$cps = $this->current_problems; // problems in the currently selected test

foreach ($ps as $p) {

    $edit_url = $this->url(array(
                    'controller' => 'problems',
                    'action'     => 'view',
                    'problem_id' => $p['problem_id']));

    echo "<tr>";
    echo "<td><a href=\"$edit_url\">" . $p['short_desc'] . "</a></td>";
    echo "<td>" . $p['create_date'] . "</td>";

    $add_url = $this->url(array(
                    'controller' => 'tests',
                    'action'     => 'add-problem',
                    'problem_id' => $p['problem_id']));

    if (in_array($p['problem_id'], $cps)) {
        echo "<td>in</td>";
    } else {
        echo "<td><a href=\"$add_url\">add</a></td>";
    }

    echo "</tr>";
}

$new_url = $this->url(array(
                'controller' => 'problems',
                'action'     => 'new',),
            null, true);

echo "<tr><td colspan=\"3\"><a href=\"$new_url\">create new problem</a></td></tr>";


echo "</table>";
echo "</div>";

?>

